name: build

on: 
  push: 
    branches: [ "main" ]

jobs:
  linux-x64:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        architecture: [ x64 ]
        os: [ linux ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 
    - run: |
        cd isl 
        ./autogen.sh
        ./configure --prefix=`pwd`/install --with-clang=no --with-int=imath
        make install
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}_${{ matrix.architecture }}
        path: |
          ./install/lib/**/*
        if-no-files-found: error
  
